StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{6498D02D82D9022C}" {
   Id "#SesM-Description_Phel_ass_desc"
   Target_en_us "Russian Forces are preparing St. Phellipe assault."\
   "Town control points are: Admin building, Factory and Hotel. Freeze time: 5 mikes."
   Target_ru_ru "ВСРФ готовит штурм Сант-Филипа. Контроль над городом обеспечивают 3 здания: Администрация, Фабрика и Отель. Фризтайм 5 минут."
   Status TRANSLATION_DONE
   Modified 1687737122
   Author "USER"
   LastChanged "USER"
  }
  CustomStringTableItem "{6498F0902A4EBAE2}" {
   Id "Sesm_AFRF_Tasks"
   Target_en_us "Russian Forces objectives"
   Target_ru_ru "Задачи ВС РФ"
   Modified 1687746462
   Author "USER"
   LastChanged "USER"
  }
  CustomStringTableItem "{6498F097FD02689C}" {
   Id "Sesm_philass_descr_afrf_task_1"
   Target_en_us "Secure designated buildings in St. Phillipe."\
   ""\
   "Additional equipment located in the vehicles' storage."
   Target_ru_ru "Задача: Зачистить отмеченные здания в городе."\
   ""\
   "Обратите внимание на содержимое вашей техники."
   Modified 1687746845
   Author "USER"
   LastChanged "USER"
  }
  CustomStringTableItem "{6498F0904C28513D}" {
   Id "Sesm_philass_descr_misdescr"
   Target_en_us "Russian Forces are preparing St. Phellipe assault."\
   ""\
   "Town control points are: Admin building, Factory and Hotel. "\
   ""\
   "Freeze time: 5 mikes."
   Target_ru_ru "ВСРФ готовит штурм Сант-Филипа. "\
   ""\
   "Контроль над городом обеспечивают 3 здания: Администрация, Фабрика и Отель. "\
   ""\
   "Фризтайм 5 минут."
   Modified 1687746862
   Author "USER"
   LastChanged "USER"
  }
  CustomStringTableItem "{6498F0925B6A607F}" {
   Id "Sesm_philass_descr_usmc_task"
   Target_en_us "USMC objectives"
   Target_ru_ru "Задачи КМП США"
   Modified 1687745546
   Author "USER"
   LastChanged "USER"
  }
  CustomStringTableItem "{6498F091F83E02FE}" {
   Id "Sesm_philass_descr_usmc_task_1"
   Target_en_us "Secure designated buildings in control."\
   ""\
   "During freezetime movement is limited by town perimeter."\
   ""\
   "Additional assets stored in the vehicles' cargo."
   Target_ru_ru "Задача: Удержать как можно больше отмеченых зданий в городе. По городу можно перемещаться и до окончания фризтайма! Обратите внимание на содержимое вашей техники."
   Modified 1687746885
   Author "USER"
   LastChanged "USER"
  }
 }
}